version: "3.9"

services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    command:
      - "--ping"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=npipe:////./pipe/docker_engine"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=C:/etc/traefik/config/dynamic"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
    ports:
      - "443:443"
      - "8079:8080"
      - "80:80"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
    volumes:
      - source: \\.\pipe\docker_engine\
        target: \\.\pipe\docker_engine\
        type: npipe
      - ./docker/traefik:C:/etc/traefik
    depends_on:
      web:
        condition: service_started
  web:
    image: ${WEB_IMAGE}
    entrypoint: powershell.exe -NoLogo -NoProfile -File C:\\startup\\startup.ps1
    volumes:
      - .\docker\web\startup:C:\startup:ro
      - .\docker\traefik\certs:C:\certs:ro
    environment:
      HOST_HEADER: ${HOST_HEADER}
    networks:
      default:
        aliases: [ "${WEB_HOST}" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.force-STS-Header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.force-STS-Header.headers.stsSeconds=31536000"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=Host(`${WEB_HOST}`)"
      - "traefik.http.routers.web-secure.entrypoints=websecure"
      - "traefik.http.routers.web-secure.rule=Host(`${WEB_HOST}`)"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.middlewares=force-STS-Header"
  whw:
    image: ${WHW_IMAGE}
    volumes: 
      - C:\windows\system32\drivers\etc:C:\driversetc
      - source: \\.\pipe\docker_engine\
        target: \\.\pipe\docker_engine\
        type: npipe
    environment:
      TERMINATION_MAP: web:traefik